import Footer from '@/components/Footer'
import Navbar from '@/components/Navbar'
import '@/styles/globals.css'
import Head from 'next/head'

export default function App({ Component, pageProps }) {
  return <>
    <Head>
      <title>Hunting Coder</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="keywords" content="next js, hunting coder, huntingcoder blog, blog" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    x
    <Navbar />
    <Component {...pageProps} />
    <Footer />
  </>
}
